export const DATA_DIR_PATH = "./data"
export const INPUT_FILE_NAME = "input.txt"
export const OUTPUT_FILE_NAME = "output.txt"
export const TEST_RESULT_FILE_NAME = "test-result.txt"

export const INPUT_PATH = `${DATA_DIR_PATH}/${INPUT_FILE_NAME}`
export const OUTPUT_PATH = `${DATA_DIR_PATH}/${OUTPUT_FILE_NAME}`
export const TEST_RESULT_PATH = `${DATA_DIR_PATH}/${TEST_RESULT_FILE_NAME}`


/**
 * Amount of strings generated by MockDataCreator class when running
 * <create> command
 * @date 26/07/2023 - 13:44:20
 *
 * @type {number}
 */
export const MOCK_DATA_AMOUNT: number = 1e5


/**
 * Separator used in testing environment.
 * Space is used, because it's visually easier to create and test strings/chunks
 * separated by spaces
 * If you change it, most of the test would break
 * @date 26/07/2023 - 13:46:11
 *
 * @type {" "}
 */
export const SEPARATOR_TEST: " " = " "


/**
 * Character used to separate symbols in input file.
 * If you provide your own test file make sure to put correct separator here.
 * Attention: change only character in "else" condition,
 * otherwise it can break the tests
 * @date 26/07/2023 - 13:48:20
 *
 * @type {string}
 */
export const SEPARATOR_IN: string = process.env["TEST"] === "true" ? SEPARATOR_TEST : " "

/**
 * Character used to separate symbols in output file.
 * Attention: change only character in "else" condition,
 * otherwise it can break the tests
 * @date 26/07/2023 - 13:48:20
 *
 * @type {string}
 */
export const SEPARATOR_OUT: string = process.env["TEST"] === "true" ? SEPARATOR_TEST : "\n"